import type { Question, Challenge, ChallengeWithMyStatus, User, Friend, Letter, Nomination } from '@/types';

export const MOCK_USER: User = {
  id: 'user-1',
  email: 'hello@example.com',
  nickname: '하늘',
  profile_image_url: null,
  school: '서울고등학교',
  challenge_create_remaining: 2,
  fcm_token: null,
  status: 'active',
  created_at: '2026-02-20T10:00:00Z',
  updated_at: '2026-02-20T10:00:00Z',
};

const QUESTION_META = { is_active: true as const, usage_count: 0, created_at: '2026-01-01T00:00:00Z' };

export const MOCK_QUESTIONS: Question[] = [
  // #설렘 (crush) - 18개
  { id: 'q1', category: 'crush', question_text: '썸 탄다면 제일 먼저 떠오르는 사람은?', ...QUESTION_META },
  { id: 'q2', category: 'crush', question_text: '프사 바꾸면 제일 먼저 확인할 것 같은 사람은?', ...QUESTION_META },
  { id: 'q3', category: 'crush', question_text: '이 사람이랑 같은 반이면 학교 매일 가고 싶을 사람은?', ...QUESTION_META },
  { id: 'q4', category: 'crush', question_text: '카톡 올 때마다 괜히 심장 뛰는 사람은?', ...QUESTION_META },
  { id: 'q5', category: 'crush', question_text: '우연히 길에서 마주치면 하루종일 기분 좋을 사람은?', ...QUESTION_META },
  { id: 'q6', category: 'crush', question_text: '인스타 스토리 올리면 봐줬으면 하는 사람은?', ...QUESTION_META },
  { id: 'q7', category: 'crush', question_text: '옆자리에 앉으면 집중 못 할 것 같은 사람은?', ...QUESTION_META },
  { id: 'q8', category: 'crush', question_text: '비 오는 날 같이 걷고 싶은 사람은?', ...QUESTION_META },
  { id: 'q9', category: 'crush', question_text: '잠들기 전 마지막으로 생각나는 사람은?', ...QUESTION_META },
  { id: 'q10', category: 'crush', question_text: '눈 마주치면 먼저 피하게 되는 사람은?', ...QUESTION_META },
  { id: 'q11', category: 'crush', question_text: '커플 틱톡 같이 찍고 싶은 사람은?', ...QUESTION_META },
  { id: 'q12', category: 'crush', question_text: '아무도 모르게 검색해본 적 있는 사람은?', ...QUESTION_META },
  { id: 'q13', category: 'crush', question_text: '같이 노을 보고 싶은 사람은?', ...QUESTION_META },
  { id: 'q14', category: 'crush', question_text: '심쿵한 적 있는 사람은?', ...QUESTION_META },
  { id: 'q15', category: 'crush', question_text: '학교 끝나고 같이 돌아가고 싶은 사람은?', ...QUESTION_META },
  { id: 'q16', category: 'crush', question_text: "'좋아해'라고 말해보고 싶은 사람은?", ...QUESTION_META },
  { id: 'q17', category: 'crush', question_text: '매일 봐도 안 질릴 것 같은 사람은?', ...QUESTION_META },
  { id: 'q18', category: 'crush', question_text: '솔직히 내 마음 들킬까봐 조심하게 되는 사람은?', ...QUESTION_META },

  // #찐친 (bestie) - 18개
  { id: 'q19', category: 'bestie', question_text: "새벽 3시에 '나와' 하면 진짜 나올 친구는?", ...QUESTION_META },
  { id: 'q20', category: 'bestie', question_text: '내 폰 검사해도 괜찮은 친구는?', ...QUESTION_META },
  { id: 'q21', category: 'bestie', question_text: '같이 살면 진짜 재밌을 것 같은 친구는?', ...QUESTION_META },
  { id: 'q22', category: 'bestie', question_text: '카톡 프사 못생기게 찍어도 화 안 낼 친구는?', ...QUESTION_META },
  { id: 'q23', category: 'bestie', question_text: '시험 망해도 같이 있으면 괜찮아지는 친구는?', ...QUESTION_META },
  { id: 'q24', category: 'bestie', question_text: '내 흑역사 다 알지만 안 퍼뜨리는 친구는?', ...QUESTION_META },
  { id: 'q25', category: 'bestie', question_text: '급식 같이 먹으면 제일 행복한 친구는?', ...QUESTION_META },
  { id: 'q26', category: 'bestie', question_text: '울 때 아무 말 없이 옆에 있어줄 친구는?', ...QUESTION_META },
  { id: 'q27', category: 'bestie', question_text: '여행 가면 한 방 쓰고 싶은 친구는?', ...QUESTION_META },
  { id: 'q28', category: 'bestie', question_text: '5년 뒤에도 연락하고 있을 친구는?', ...QUESTION_META },
  { id: 'q29', category: 'bestie', question_text: '내 TMI 다 들어주는 친구는?', ...QUESTION_META },
  { id: 'q30', category: 'bestie', question_text: '같이 밤새 넷플릭스 정주행할 친구는?', ...QUESTION_META },
  { id: 'q31', category: 'bestie', question_text: '내가 잘못해도 솔직하게 말해줄 친구는?', ...QUESTION_META },
  { id: 'q32', category: 'bestie', question_text: '롤/배그 듀오 하고 싶은 친구는?', ...QUESTION_META },
  { id: 'q33', category: 'bestie', question_text: '카페에서 아무 말 없이 같이 있어도 편한 친구는?', ...QUESTION_META },
  { id: 'q34', category: 'bestie', question_text: '졸업해도 꼭 연락하고 싶은 친구는?', ...QUESTION_META },
  { id: 'q35', category: 'bestie', question_text: '나 대신 발표해줄 것 같은 찐친은?', ...QUESTION_META },
  { id: 'q36', category: 'bestie', question_text: '인생 힘들 때 전화 한 통이면 달려올 친구는?', ...QUESTION_META },

  // #TMI (tmi) - 18개
  { id: 'q37', category: 'tmi', question_text: '전생에 뭐였을지 제일 궁금한 사람은?', ...QUESTION_META },
  { id: 'q38', category: 'tmi', question_text: 'MBTI 안 물어봐도 다 아는 것 같은 사람은?', ...QUESTION_META },
  { id: 'q39', category: 'tmi', question_text: '잠버릇이 제일 궁금한 사람은?', ...QUESTION_META },
  { id: 'q40', category: 'tmi', question_text: '핸드폰 배터리 몇 %에서 충전하는지 궁금한 사람은?', ...QUESTION_META },
  { id: 'q41', category: 'tmi', question_text: '어릴 때 장래희망이 뭐였는지 궁금한 사람은?', ...QUESTION_META },
  { id: 'q42', category: 'tmi', question_text: '유튜브 알고리즘이 제일 궁금한 사람은?', ...QUESTION_META },
  { id: 'q43', category: 'tmi', question_text: '첫사랑이 누구였는지 궁금한 사람은?', ...QUESTION_META },
  { id: 'q44', category: 'tmi', question_text: '가장 최근에 운 이유가 궁금한 사람은?', ...QUESTION_META },
  { id: 'q45', category: 'tmi', question_text: '혼자 있을 때 뭐 하는지 궁금한 사람은?', ...QUESTION_META },
  { id: 'q46', category: 'tmi', question_text: '잠들기 전에 무슨 생각하는지 궁금한 사람은?', ...QUESTION_META },
  { id: 'q47', category: 'tmi', question_text: '인생 좌우명이 궁금한 사람은?', ...QUESTION_META },
  { id: 'q48', category: 'tmi', question_text: '제일 좋아하는 노래가 궁금한 사람은?', ...QUESTION_META },
  { id: 'q49', category: 'tmi', question_text: '브이로그 찍으면 제일 재밌을 것 같은 사람은?', ...QUESTION_META },
  { id: 'q50', category: 'tmi', question_text: '감춰진 재능이 있을 것 같은 사람은?', ...QUESTION_META },
  { id: 'q51', category: 'tmi', question_text: '연애 스타일이 궁금한 사람은?', ...QUESTION_META },
  { id: 'q52', category: 'tmi', question_text: '되고 싶은 게 뭔지 궁금한 사람은?', ...QUESTION_META },
  { id: 'q53', category: 'tmi', question_text: '가방 안에 뭐 들었는지 궁금한 사람은?', ...QUESTION_META },
  { id: 'q54', category: 'tmi', question_text: '최근 빠진 것(최애)이 궁금한 사람은?', ...QUESTION_META },

  // #고마움 (thanks) - 16개
  { id: 'q55', category: 'thanks', question_text: '존재 자체가 힐링인 사람은?', ...QUESTION_META },
  { id: 'q56', category: 'thanks', question_text: '아무 말 없이 옆에만 있어도 위로가 되는 사람은?', ...QUESTION_META },
  { id: 'q57', category: 'thanks', question_text: '올해 진짜 없었으면 큰일 났을 사람은?', ...QUESTION_META },
  { id: 'q58', category: 'thanks', question_text: '웃겨서 배 아플 정도로 웃게 해준 사람은?', ...QUESTION_META },
  { id: 'q59', category: 'thanks', question_text: "'너 아니었으면 어쩔 뻔했어' 싶은 사람은?", ...QUESTION_META },
  { id: 'q60', category: 'thanks', question_text: '힘든 날 한마디로 살려준 사람은?', ...QUESTION_META },
  { id: 'q61', category: 'thanks', question_text: '작은 거 하나도 챙겨줘서 감동이었던 사람은?', ...QUESTION_META },
  { id: 'q62', category: 'thanks', question_text: '믿어줘서 용기 낼 수 있었던 사람은?', ...QUESTION_META },
  { id: 'q63', category: 'thanks', question_text: '내가 울 때 같이 울어준 사람은?', ...QUESTION_META },
  { id: 'q64', category: 'thanks', question_text: '포기하려 할 때 붙잡아준 사람은?', ...QUESTION_META },
  { id: 'q65', category: 'thanks', question_text: '아침에 일어나면 연락 와 있어서 기분 좋은 사람은?', ...QUESTION_META },
  { id: 'q66', category: 'thanks', question_text: '나를 있는 그대로 좋아해주는 사람은?', ...QUESTION_META },
  { id: 'q67', category: 'thanks', question_text: "'고마워'라고 꼭 말하고 싶은 사람은?", ...QUESTION_META },
  { id: 'q68', category: 'thanks', question_text: '내 편이라서 든든한 사람은?', ...QUESTION_META },
  { id: 'q69', category: 'thanks', question_text: '덕분에 올해가 좋았다고 말하고 싶은 사람은?', ...QUESTION_META },
  { id: 'q70', category: 'thanks', question_text: '나한테 좋은 영향을 준 사람은?', ...QUESTION_META },

  // #만약에 (whatif) - 16개
  { id: 'q71', category: 'whatif', question_text: '좀비 아포칼립스에서 같이 살아남고 싶은 사람은?', ...QUESTION_META },
  { id: 'q72', category: 'whatif', question_text: '무인도에 딱 한 명 데려간다면?', ...QUESTION_META },
  { id: 'q73', category: 'whatif', question_text: '타임머신 타고 같이 과거로 가고 싶은 사람은?', ...QUESTION_META },
  { id: 'q74', category: 'whatif', question_text: '로또 당첨되면 제일 먼저 알려줄 사람은?', ...QUESTION_META },
  { id: 'q75', category: 'whatif', question_text: '같이 세계여행 떠나고 싶은 사람은?', ...QUESTION_META },
  { id: 'q76', category: 'whatif', question_text: '영화 속 주인공이 되면 상대역 시키고 싶은 사람은?', ...QUESTION_META },
  { id: 'q77', category: 'whatif', question_text: '초능력 하나 줄 수 있다면 주고 싶은 사람은?', ...QUESTION_META },
  { id: 'q78', category: 'whatif', question_text: '같이 유튜브 채널 하면 대박 날 것 같은 사람은?', ...QUESTION_META },
  { id: 'q79', category: 'whatif', question_text: '1일만 몸이 바뀐다면 바뀌고 싶은 사람은?', ...QUESTION_META },
  { id: 'q80', category: 'whatif', question_text: '같은 꿈을 꿀 수 있다면 같이 꾸고 싶은 사람은?', ...QUESTION_META },
  { id: 'q81', category: 'whatif', question_text: '세상에 나랑 둘만 남으면 그나마 괜찮을 사람은?', ...QUESTION_META },
  { id: 'q82', category: 'whatif', question_text: '같이 밴드 하면 찰떡일 것 같은 사람은?', ...QUESTION_META },
  { id: 'q83', category: 'whatif', question_text: '다음 생에도 다시 만나고 싶은 사람은?', ...QUESTION_META },
  { id: 'q84', category: 'whatif', question_text: '같이 카페 창업하면 잘 될 것 같은 사람은?', ...QUESTION_META },
  { id: 'q85', category: 'whatif', question_text: '내가 아이돌이면 팬 해줄 것 같은 사람은?', ...QUESTION_META },
  { id: 'q86', category: 'whatif', question_text: '비밀지도를 발견하면 같이 모험 떠날 사람은?', ...QUESTION_META },

  // #솔직히 (real) - 16개
  { id: 'q87', category: 'real', question_text: '솔직히 질투 난 적 있는 사람은?', ...QUESTION_META },
  { id: 'q88', category: 'real', question_text: "처음 봤을 때 '이 사람 뭐지?' 했던 사람은?", ...QUESTION_META },
  { id: 'q89', category: 'real', question_text: '같이 있으면 나도 모르게 신경 쓰이는 사람은?', ...QUESTION_META },
  { id: 'q90', category: 'real', question_text: '뒤에서 칭찬한 적 있는 사람은?', ...QUESTION_META },
  { id: 'q91', category: 'real', question_text: '솔직히 나보다 잘하는 것 같아서 자극 되는 사람은?', ...QUESTION_META },
  { id: 'q92', category: 'real', question_text: '첫인상이랑 지금이랑 제일 다른 사람은?', ...QUESTION_META },
  { id: 'q93', category: 'real', question_text: '알고 보니 의외로 다정한 사람은?', ...QUESTION_META },
  { id: 'q94', category: 'real', question_text: '가끔 멋있다고 느낀 적 있는 사람은?', ...QUESTION_META },
  { id: 'q95', category: 'real', question_text: '닮고 싶은 부분이 있는 사람은?', ...QUESTION_META },
  { id: 'q96', category: 'real', question_text: '한 번쯤 속마음을 들어보고 싶은 사람은?', ...QUESTION_META },
  { id: 'q97', category: 'real', question_text: "'나한테 관심 있나?' 헷갈렸던 사람은?", ...QUESTION_META },
  { id: 'q98', category: 'real', question_text: '오해한 적 있었는데 알고 보니 좋은 사람이었던 사람은?', ...QUESTION_META },
  { id: 'q99', category: 'real', question_text: "가끔 '이 사람 왜 이렇게 웃기지' 하는 사람은?", ...QUESTION_META },
  { id: 'q100', category: 'real', question_text: '은근 경쟁심 느끼는 사람은?', ...QUESTION_META },
  { id: 'q101', category: 'real', question_text: '진짜 속마음이 궁금한 사람은?', ...QUESTION_META },
  { id: 'q102', category: 'real', question_text: '나를 어떻게 생각하는지 제일 궁금한 사람은?', ...QUESTION_META },
];

const futureDate = new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString();
const pastDate = new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString();

export const MOCK_CHALLENGES: ChallengeWithMyStatus[] = [
  {
    id: 'ch-1',
    question_id: 'q1',
    question: MOCK_QUESTIONS[0],
    creator_id: 'user-1',
    status: 'active',
    participant_count: 8,
    max_participants: 30,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    expires_at: futureDate,
    my_status: 'completed',
    my_role: 'host',
    my_participant_order: 3,
    participant_display: '서준 외 7명',
  },
  {
    id: 'ch-2',
    question_id: 'q19',
    question: MOCK_QUESTIONS[18],
    creator_id: 'user-3',
    status: 'active',
    participant_count: 5,
    max_participants: 30,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 42 * 60 * 60 * 1000).toISOString(),
    my_status: 'my_turn',
    my_role: 'participant',
    participant_display: '민서 외 4명',
  },
  {
    id: 'ch-3',
    question_id: 'q87',
    question: MOCK_QUESTIONS[86],
    creator_id: 'user-1',
    status: 'result_delivered',
    participant_count: 12,
    max_participants: 30,
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    expires_at: pastDate,
    my_status: 'completed',
    my_role: 'host',
    my_participant_order: 5,
    participant_display: '지우 외 11명',
  },
];

/** Per-challenge participant user IDs (already in chain); used to show "이미 참여 중" and disable selection */
export const MOCK_CHALLENGE_PARTICIPANT_IDS: Record<string, string[]> = {
  'ch-1': ['user-1', 'user-2', 'user-4', 'user-5', 'user-8'],
  'ch-2': ['user-3', 'user-1'],
  'ch-3': ['user-1', 'user-2', 'user-3', 'user-5', 'user-8'],
};

export const MOCK_FRIENDS: Friend[] = [
  { id: 'user-2', nickname: '서준', profile_image_url: null, is_app_user: true },
  { id: 'user-3', nickname: '민서', profile_image_url: null, is_app_user: true },
  { id: 'user-4', nickname: '지우', profile_image_url: null, is_app_user: true },
  { id: 'user-5', nickname: '수빈', profile_image_url: null, is_app_user: true },
  { id: 'user-6', nickname: '예린', profile_image_url: null, is_app_user: false, phone_last4: '1234' },
  { id: 'user-7', nickname: '도윤', profile_image_url: null, is_app_user: false, phone_last4: '5678' },
  { id: 'user-8', nickname: '하은', profile_image_url: null, is_app_user: true },
  { id: 'user-9', nickname: '시우', profile_image_url: null, is_app_user: false, phone_last4: '9012' },
  { id: 'user-10', nickname: '윤아', profile_image_url: null, is_app_user: true },
  { id: 'user-11', nickname: '준혁', profile_image_url: null, is_app_user: true },
];

export const MOCK_LETTERS: (Letter & { challenge_question?: string })[] = [
  {
    id: 'letter-1',
    challenge_id: 'ch-3',
    nomination_id: 'nom-5',
    sender_id: 'user-3',
    receiver_id: 'user-1',
    content: '네가 옆에 있어주는 것만으로도 힘이 돼. 항상 고맙고, 앞으로도 지금처럼 좋은 사이로 지내자. 힘들 때 항상 먼저 연락해주는 너의 따뜻한 마음을 잊지 못할 거야.',
    is_revealed: false,
    is_reported: false,
    is_blinded: false,
    created_at: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
    challenge_question: '첫인상과 지금 인상이 가장 다른 사람은?',
  },
  {
    id: 'letter-2',
    challenge_id: 'ch-3',
    nomination_id: 'nom-8',
    sender_id: 'user-5',
    receiver_id: 'user-1',
    content: '처음 만났을 때는 조용한 사람인 줄 알았는데 알고 보니 누구보다 유쾌하고 따뜻한 사람이더라. 그 반전이 좋아서 더 친해지고 싶었어.',
    is_revealed: true,
    is_reported: false,
    is_blinded: false,
    created_at: new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString(),
    challenge_question: '첫인상과 지금 인상이 가장 다른 사람은?',
    sender: { id: 'user-5', nickname: '수빈', profile_image_url: null } as User,
  },
];
